FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /tests
COPY ["test/CategoryCommandTests/CategoryCommandTests.csproj","tests/CategoryCommandTests/"]
COPY ["test/ProductCommandTests/ProductCommandTests.csproj","tests/ProductCommandTests/"]
COPY ["test/SupplierCommandTests/SupplierCommandTests.csproj","tests/SupplierCommandTests/"]